### PR TITLE
Add support for Python 3.6 and Django 2.0

### PR DESCRIPTION
**Pull request by SunilMohanAdapa**
Signed-off-by: Sunil Mohan Adapa <sunil@medhas.org>

Debian is moving to Django 2.0 soon and django-bootstrap-form needs to work with Django 2.0. Many applications such as FreedomBox using will have problem otherwise.

Please merge this patch and make a new release so that we can package for Debian immediately. Thank you in advance.

### CODE REVIEW

**Comment by SunilMohanAdapa** [comment]
Would be nice to have this soon. Thanks.

**Comment by SunilMohanAdapa** [comment]
Any update on merging this?

**Comment by jarussi-luizalabs** [comment]
this is a really nice feature! 👏 👏

**Comment by tzangms** [comment]
Hi @SunilMohanAdapa @jarussi-luizalabs Sorry for the late reply, I just merged and released a new version on PyPI: https://pypi.org/project/django-bootstrap-form/3.4/

**Comment by SunilMohanAdapa** [comment]
Thank you for the merge. Debian packaging has been prepared and is ready to uploaded.

**Pull request merged**
